apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: task-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: task-proxy
    spec:
      containers:
      - name: envoy
        image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
        args: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster", "edge-proxy"]
        ports:
        - name: http
          containerPort: 8080
        - name: admin
          containerPort: 9901
        readinessProbe:
          httpGet:
            path: /ready
            port: 9901
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /server_info
            port: 9901
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
        {{- if .Values.tls.enabled }}
        - name: cert
          mountPath: /etc/certs
        {{- end }}
        {{- with .Values.proxy.resources }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{- end }}
      - name: server
        image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
        command: ["./server"]
        args:
        - "-yt-token-path=/etc/yt/token" 
        - "-namespace={{ .Release.Namespace }}"
        - "-base-domain={{ .Values.baseDomain }}"
        - "-dir-path={{ .Values.dirPath }}"
        - "-discovery-period-seconds={{ .Values.discoveryPeriodSeconds }}"
        - "-auth-enabled={{ .Values.auth.enabled }}"
        - "-auth-cookie-name={{ .Values.auth.cookieName }}"
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: token
          mountPath: /etc/yt
        {{- with .Values.server.resources }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: envoy-config
        configMap:
          name: {{ .Release.Name }}-config
          items:
          - key: envoy.yaml
            path: envoy.yaml
      - name: token
        secret:
          secretName: {{ .Values.tokenSecretRef }}
      {{- if .Values.tls.enabled }}
      - name: cert
        secret:
          secretName: {{ .Values.tls.certSecretRef }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}